apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-aladdin-appset
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys: [name] # ie. padm-tkgi-hal, bis-aks-astra-mnlw1, etc.
      generators:
      - matrix: # Base Items
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
      - matrix: # Jurisdiction Overrides
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    kubernetes.cnp.io/cluster.jurisdiction: '{{path.basename}}'
      - matrix: # Segment Overrides
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    kubernetes.cnp.io/cluster.segment: '{{path.basename}}'
      - matrix: # Environment Overrides
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    kubernetes.cnp.io/environment: '{{path.basename}}'
      - matrix: # Region Overrides
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    kubernetes.cnp.io/cluster.region: '{{path.basename}}'
      - matrix: # Per-Cluster Overrides
          generators:
            - git:
                repoURL: https://github.com/KojoRising/argo-cd.git
                revision: feat/test-cnp-appset-1
                files:
                  - path: "cnp-appset/config/**/*.yaml"
            - clusters:
                selector:
                  matchLabels:
                    argocd.argoproj.io/secret-type: cluster
                    kubernetes.cnp.io/cluster.name: '{{path.basename}}'
  template:
    metadata:
      name: 'fake-appset-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/KojoRising/argo-cd.git
        targetRevision: HEAD
        path: 'applicationset/examples/matrix/cluster-addons/argo-workflows'
        kustomize:
          namePrefix: '{{path.basename}}'
      destination:
        server: '{{server}}'
        namespace: default
